[package]
name = "rustlang"
version = "0.1.0"
authors = ["Peter Heiss <peter.heiss@uni-muenster.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
